name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.1.4
  - pip=20.3.3
  - mlflow=1.14.1
  - scikit-learn=0.24.1
  - pip:
      - wandb==0.10.21
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow.git#egg=wandb-utils&subdirectory=project/solution/components
